name: pyco 
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python>=3.8
  - munkres>=1.1.1
  - pip
  - bpython
  - pytest>=6.0
  - pytest-cov>=3.0.0
  - mypy
  - bpython
  - ruff
